#heading(
  numbering: none,
  outlined: false,
  [Danh sách từ viết tắt],
)

#table(
  columns: (auto, 1fr),
  align: left + horizon,
  [*Ký hiệu*], [*Ý nghĩa*],
  [ABAC], [Attribute-Based Access Control],
  [ACL], [Access Control List],
  [API], [Application Programming Interface],
  [CDC], [Change Data Capture],
  [CI/CD], [Continuous Integration/Continuous Deployment],
  [CLI], [Command-Line Interface],
  [CRDT], [Conflict-free Replicated Data Type],
  [CSS], [Cascading Style Sheets],
  [DOM], [Document Object Model],
  [DX], [Developer Experience],
  [HTTP/2], [Hypertext Transfer Protocol Version 2],
  [ISR], [Incremental Static Regeneration],
  [JSX], [JavaScript XML Syntax Extension],
  [Nx], [Monorepo Framework],
  [OAuth2], [OAuth 2.0 Authorization Framework],
  [OIDC], [OpenID Connect],
  [ORM], [Object-Relational Mapping],
  [OTLP], [OpenTelemetry Protocol],
  [OpenAPI], [Open API Specification],
  [OpenTelemetry], [Open Telemetry Framework],
  [Protobuf], [Protocol Buffers],
  [RBAC], [Role-Based Access Control],
  [REST], [Representational State Transfer],
  [RPC], [Remote Procedure Call],
  [SEO], [Search Engine Optimization],
  [SQL], [Structured Query Language],
  [SQLC], [SQL Compiler for Type-Safe Code Generation],
  [SSE], [Server-Sent Events],
  [SSG], [Static Site Generation],
  [SSO], [Single Sign-On],
  [SSR], [Server-Side Rendering],
  [TOML], [Tom's Obvious, Minimal Language],
  [TSX], [TypeScript XML Syntax Extension],
  [UML], [Unified Modeling Language],
  [gRPC], [Google Remote Procedure Call],
)
