#heading(
  numbering: none,
  outlined: false,
  [Danh mục từ viết tắt],
)

#table(
  columns: (auto, 1fr),
  align: left + horizon,
  [*Ký hiệu*], [*Ý nghĩa*],
  [AHP], [Analytic Hierarchy Process],
  [AI], [Artificial Intelligence],
  [API], [Application Programming Interface],
  [CDN], [Content Delivery Network],
  [CI/CD], [Continuous Integration/Continuous Deployment],
  [CORS], [Cross-Origin Resource Sharing],
  [CRUD], [Create, Read, Update, Delete],
  [CSS], [Cascading Style Sheets],
  [DOM], [Document Object Model],
  [DTO], [Data Transfer Object],
  [ERD], [Entity-Relationship Diagram],
  [FK], [Foreign Key],
  [HITL], [Human-In-The-Loop],
  [HTML], [HyperText Markup Language],
  [HTTP], [HyperText Transfer Protocol],
  [HTTPS], [HyperText Transfer Protocol Secure],
  [JAR], [Java ARchive],
  [JPA], [Java Persistence API],
  [JRE], [Java Runtime Environment],
  [JSON], [JavaScript Object Notation],
  [JSONB], [JSON Binary],
  [JVM], [Java Virtual Machine],
  [JWT], [JSON Web Token],
  [LLM], [Large Language Model],
  [LTS], [Long-Term Support],
  [OOO], [Out Of Office],
  [OpenAPI], [Open API Specification],
  [PK], [Primary Key],
  [PM], [Project Manager],
  [RAG], [Retrieval-Augmented Generation],
  [RAM], [Random Access Memory],
  [RDBMS], [Relational Database Management System],
  [REST], [Representational State Transfer],
  [S3], [Simple Storage Service],
  [SDK], [Software Development Kit],
  [SMTP], [Simple Mail Transfer Protocol],
  [SPA], [Single Page Application],
  [SQL], [Structured Query Language],
  [SSE], [Server-Sent Events],
  [UI], [User Interface],
  [UML], [Unified Modeling Language],
  [URL], [Uniform Resource Locator],
  [WIP], [Work In Progress],
)
